<?php

include_once drupal_get_path('module', 'fba_solution_pack_measurement') . '/processCSV.inc';
/**
 * @file
 * Module for importing objects from cds/isis xml file.
 *
 * @author simonfox
 * @author annajordanous
 */

/**
 * Provide definitions for menu callbacks.
 *
 * @return array
 *   Callback definitions
 */
function fba_solution_pack_measurement_menu() {
  $items = array();

  $items['fba/measurement'] = array(
    'title' => 'Upload CSV file and check validity',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fba_solution_pack_measurement'),
    'access arguments' => array('access fba_solution_pack_measurement content'),
    'type' => MENU_CALLBACK,
    'pid' => 'fba:measurement_sub_class_cmodel',
    'label' => 'FBA content model for measurement sub class',
    'dsid' => 'ISLANDORACM',
    'datastream_file' => "$module_path/xml/measurement_sub_class_cmodel.xml",
    'cmodel' => 'fedora-system:ContentModel-3.0',
  );

  return $items;
}

/**
 * Valid permissions for this module.
 *
 * @return array
 *   An array of valid permissions for the relationship_reference module
 */
function fba_solution_pack_measurement_perm() {
  return array('access fba_solution_pack_measurement content');
}
